#image: Visual Studio 2015 - GCE
environment:
  website_name: aspnetcorespa
  website_psw:
    secure: twePnoXZKws9fnk2LMHNBO7AFl7Lkl6oiEq6SHFKkDUxHDakKM56umRYI7qCz2X4QlknC+ko1JwpphPAfl9p3g==
  nodejs_version: "5.5.0"

branches:
  only:
    - appveyor
    # Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm typings
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install
  - typings install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - node -e 'console.log(process.env);'
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

# scripts to run after tests
after_test:
  - npm build:prod                                                      # Client production artefacts

cache:
  - node_modules -> package.json                                        # local npm modules

before_build:
  - dotnet restore

build:
  parallel: true
  verbosity: minimal

after_build:
  - dotnet publish .\ --output %appveyor_build_folder%\dist --configuration Release

artifacts:
  - path: dist
    name: web-app

deploy_script:
  - '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:IisApp=''%appveyor_build_folder%\dist'' -dest:IisApp=''%website_name%'',ComputerName=''https://%website_name%.scm.azurewebsites.net/msdeploy.axd'',UserName=''$%website_name%'',Password=''%website_psw%'',IncludeAcls=''False'',AuthType=''Basic'' -verb:sync -enablerule:AppOffline -enableRule:DoNotDeleteRule -retryAttempts:2'
