version: "3.6"

services:
  aspnetcorespaweb:
    image: ${DOCKER_REGISTRY}aspnetcorespaweb
    build:
      context: .
      dockerfile: src/AspNetCoreSpa.Web/Dockerfile
    environment:
      - IDENTITY_SERVER_ENDPOINT=https://aspnetcorests.azurewebsites.net
    ports:
      - 5005:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
