name: STS

on:
  push:
    branches:
    - master

jobs:
  build_aspnetcorests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'aspnetcorests' }}
      run: |
        docker build -t $APP_NAME -f src/AspNetCoreSpa.STS/Dockerfile .
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME