name: Web

on:
  push:
    branches:
    - master

jobs:
  build_aspnetcorespa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'aspnetcorespa' }}
      run: |
        docker build -t $APP_NAME -f src/AspNetCoreSpa.Web/Dockerfile .
        docker tag $APP_NAME registry.heroku.com/$APP_NAME/web
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker push registry.heroku.com/$APP_NAME/web
        heroku container:release web -a $APP_NAME